import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WordContext from "./contexts/WordContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WordContext>
        <body className={inter.className}>{children}</body>
      </WordContext>
    </html>
  );
}
